services:
  traefik:
    image: traefik:v2.4
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--log.level=DEBUG"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`traefik.local`)"
      - "traefik.http.routers.api.service=api@internal"
    networks:
      - gpnetwork

  postgres:
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postgres.rule=Host(`postgres.local`)"
    networks:
      - gpnetwork

  # mysql:
  #   image: mysql:8.4
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.mysql.rule=Host(`mysql.localhost`)"

  # adminer:
  #   image: adminer:5.2.1
  #   restart: always
  #   ports:
  #     - 8888:8080

networks:
  gpnetwork:
    name: gpnetwork
