services:
  service-api:
    build:
      args:
        PLATFORM: ${PLATFORM}
        IMAGE_NAME_TAG: ${IMAGE_NAME_TAG}
      context: ../../
      dockerfile: cmd/api/Dockerfile
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-service.rule=Host(`api-service.localhost`)"
      - "traefik.http.services.api-service.loadbalancer.server.port=8000"
