# Traefik static configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

api:
  dashboard: true
  # Uncomment the following line to enable insecure access to the dashboard when using Windows and WSL2
  #insecure: true

providers:
  docker: {}
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

tls:
  options:
    default:
      minVersion: "VersionTLS12"
